local AddonName, ns = ...

ns.Data = {
    Consumables = {
        Flasks = {
            [1] = "Flask of the Magisters",
            [2] = "Light's Potential",
            [3] = "Draught of Rampant Abandon",
        },
        Food = {
            [1] = "Flora Frenzy",
            [2] = "Royal Roast",
            [3] = "Quel'dorei Medley",
            [4] = "Silvermoon Parade",
        },
        Runes = {
            [1] = "Void-Touched Augment Rune",
        },
        Weapon = {
            [1] = "Thalassian Phoenix Oil",
        },
        Potions = {
            [1] = "Light's Potential",
            [2] = "Draught of Rampant Abandon",
        },
        HealthPotions = {
            [1] = "Silvermoon Health Potion",
        },
        Drums = {
            [1] = "Void-Touched Drums",
        },
        BattleRez = {
            [1] = "Emergency Soul Link",
        },
    },
    Specs = {
        DEATHKNIGHT = {
            [250] = { -- Blood (tank)
                Gems = { primary="Flawless Quick Garnet",       meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Blessing of Speed",
                    [3]  = "Enchant Shoulders - Akil'zon's Swiftness",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Farstrider's Hunt",
                    [11] = "Enchant Ring - Nature's Fury",
                    [12] = "Enchant Ring - Nature's Fury",
                    [16] = "Rune of Sanguination",
                },
            },
            [251] = { -- Frost (dps)
                Gems = { primary="Flawless Deadly Amethyst",    meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Blessing of Speed",
                    [3]  = "Enchant Shoulders - Akil'zon's Swiftness",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Farstrider's Hunt",
                    [11] = "Enchant Ring - Eyes of the Eagle",
                    [12] = "Enchant Ring - Eyes of the Eagle",
                    [16] = "Rune of Razorice",
                    [17] = "Rune of the Fallen Crusader",
                },
            },
            [252] = { -- Unholy (dps)
                Gems = { primary="Flawless Masterful Garnet",   meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Blessing of Speed",
                    [3]  = "Enchant Shoulders - Flight of the Eagle",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Farstrider's Hunt",
                    [11] = "Enchant Ring - Zul'jin's Mastery",
                    [12] = "Enchant Ring - Zul'jin's Mastery",
                    [16] = "Rune of the Apocalypse",
                },
            },
        },
        DEMONHUNTER = {
            [577] = { -- Havoc (dps)
                Gems = { primary="Flawless Masterful Garnet",   meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Eyes of the Eagle",
                    [12] = "Enchant Ring - Eyes of the Eagle",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [581] = { -- Vengeance (tank)
                Gems = { primary="Flawless Deadly Peridot",     meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Blessing of Speed",
                    [3]  = "Enchant Shoulders - Akil'zon's Swiftness",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Farstrider's Hunt",
                    [11] = "Enchant Ring - Eyes of the Eagle",
                    [12] = "Enchant Ring - Eyes of the Eagle",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                    [17] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [1480] = { -- Devourer (dps)
                Gems = { primary="Flawless Quick Amethyst",     meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Zul'jin's Mastery",
                    [12] = "Enchant Ring - Zul'jin's Mastery",
                    [16] = "Enchant Weapon - Arcane Mastery",
                    [17] = "Enchant Weapon - Berserker's Rage",
                },
            },
        },
        DRUID = {
            [102] = { -- Balance (dps)
                Gems = { primary="Flawless Quick Amethyst",     meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Zul'jin's Mastery",
                    [12] = "Enchant Ring - Zul'jin's Mastery",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [103] = { -- Feral (dps)
                Gems = { primary="Flawless Masterful Garnet",   meta="Powerful Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Zul'jin's Mastery",
                    [12] = "Enchant Ring - Zul'jin's Mastery",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [104] = { -- Guardian (tank)
                Gems = { primary="Flawless Versatile Peridot",  meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Blessing of Speed",
                    [3]  = "Enchant Shoulders - Akil'zon's Swiftness",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Farstrider's Hunt",
                    [11] = "Enchant Ring - Silvermoon's Alacrity",
                    [12] = "Enchant Ring - Silvermoon's Alacrity",
                    [16] = "Enchant Weapon - Berserker's Rage",
                },
            },
            [105] = { -- Restoration (healer)
                Gems = { primary="Flawless Masterful Peridot",  meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Hex of Leeching",
                    [3]  = "Enchant Shoulders - Silvermoon's Mending",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Arcanoweave Spellthread",
                    [8]  = "Enchant Boots - Shaladrassil's Roots",
                    [11] = "Enchant Ring - Silvermoon's Alacrity",
                    [12] = "Enchant Ring - Silvermoon's Alacrity",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
        },
        EVOKER = {
            [1467] = { -- Devastation (dps)
                Gems = { primary="Flawless Quick Garnet",       meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Nature's Fury",
                    [12] = "Enchant Ring - Nature's Fury",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [1468] = { -- Preservation (healer)
                Gems = { primary="Flawless Quick Amethyst",     meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Hex of Leeching",
                    [3]  = "Enchant Shoulders - Silvermoon's Mending",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Arcanoweave Spellthread",
                    [8]  = "Enchant Boots - Shaladrassil's Roots",
                    [11] = "Enchant Ring - Zul'jin's Mastery",
                    [12] = "Enchant Ring - Zul'jin's Mastery",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [1473] = { -- Augmentation (dps)
                Gems = { primary="Flawless Quick Garnet",       meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Nature's Fury",
                    [12] = "Enchant Ring - Nature's Fury",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
        },
        HUNTER = {
            [253] = { -- Beast Mastery (dps)
                Gems = { primary="Flawless Quick Amethyst",     meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Zul'jin's Mastery",
                    [12] = "Enchant Ring - Zul'jin's Mastery",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [254] = { -- Marksmanship (dps)
                Gems = { primary="Flawless Masterful Garnet",   meta="Powerful Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Nature's Fury",
                    [12] = "Enchant Ring - Nature's Fury",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [255] = { -- Survival (dps)
                Gems = { primary="Flawless Deadly Amethyst" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Zul'jin's Mastery",
                    [12] = "Enchant Ring - Zul'jin's Mastery",
                    [16] = "Enchant Weapon - Arcane Mastery",
                    [17] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
        },
        MAGE = {
            [62] = { -- Arcane (dps)
                Gems = { primary="Flawless Quick Amethyst",     meta="Powerful Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Silvermoon's Mending",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Arcanoweave Spellthread",
                    [8]  = "Enchant Boots - Shaladrassil's Roots",
                    [11] = "Enchant Ring - Eyes of the Eagle",
                    [12] = "Enchant Ring - Eyes of the Eagle",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [63] = { -- Fire (dps)
                Gems = { primary="Flawless Quick Amethyst",     meta="Powerful Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Eyes of the Eagle",
                    [12] = "Enchant Ring - Eyes of the Eagle",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [64] = { -- Frost (dps)
                Gems = { primary="Flawless Deadly Amethyst",    meta="Powerful Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Zul'jin's Mastery",
                    [12] = "Enchant Ring - Zul'jin's Mastery",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
        },
        MONK = {
            [268] = { -- Brewmaster (tank)
                Gems = { primary="Flawless Versatile Garnet",   meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Hex of Leeching",
                    [3]  = "Enchant Shoulders - Silvermoon's Mending",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Shaladrassil's Roots",
                    [11] = "Enchant Ring - Nature's Fury",
                    [12] = "Enchant Ring - Nature's Fury",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                    [17] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [270] = { -- Mistweaver (healer)
                Gems = { primary="Flawless Deadly Peridot",     meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Hex of Leeching",
                    [3]  = "Enchant Shoulders - Silvermoon's Mending",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Shaladrassil's Roots",
                    [11] = "Enchant Ring - Silvermoon's Alacrity",
                    [12] = "Enchant Ring - Silvermoon's Alacrity",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [269] = { -- Windwalker (dps)
                Gems = { primary="Flawless Deadly Peridot",     meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Silvermoon's Alacrity",
                    [12] = "Enchant Ring - Silvermoon's Alacrity",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
        },
        PALADIN = {
            [65] = { -- Holy (healer)
                Gems = { primary="Flawless Quick Amethyst",     meta="Telluric Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Hex of Leeching",
                    [3]  = "Enchant Shoulders - Silvermoon's Mending",
                    [5]  = "Enchant Chest - Mark of the Magister",
                    [7]  = "Arcanoweave Spellthread",
                    [8]  = "Enchant Boots - Shaladrassil's Roots",
                    [11] = "Enchant Ring - Zul'jin's Mastery",
                    [12] = "Enchant Ring - Zul'jin's Mastery",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [66] = { -- Protection (tank)
                Gems = { primary="Flawless Versatile Peridot",  meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Blessing of Speed",
                    [3]  = "Enchant Shoulders - Akil'zon's Swiftness",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Farstrider's Hunt",
                    [11] = "Enchant Ring - Silvermoon's Alacrity",
                    [12] = "Enchant Ring - Silvermoon's Alacrity",
                    [16] = "Enchant Weapon - Berserker's Rage",
                },
            },
            [70] = { -- Retribution (dps)
                Gems = { primary="Flawless Quick Amethyst",     meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Blessing of Speed",
                    [3]  = "Enchant Shoulders - Akil'zon's Swiftness",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Farstrider's Hunt",
                    [11] = "Enchant Ring - Eyes of the Eagle",
                    [12] = "Enchant Ring - Eyes of the Eagle",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
        },
        PRIEST = {
            [256] = { -- Discipline (healer)
                Gems = { primary="Flawless Deadly Peridot",     meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Hex of Leeching",
                    [3]  = "Enchant Shoulders - Silvermoon's Mending",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Shaladrassil's Roots",
                    [11] = "Enchant Ring - Silvermoon's Alacrity",
                    [12] = "Enchant Ring - Silvermoon's Alacrity",
                    [16] = "Enchant Weapon - Berserker's Rage",
                },
            },
            [257] = { -- Holy (healer)
                Gems = { primary="Flawless Versatile Garnet",   meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Hex of Leeching",
                    [3]  = "Enchant Shoulders - Silvermoon's Mending",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Shaladrassil's Roots",
                    [11] = "Enchant Ring - Nature's Fury",
                    [12] = "Enchant Ring - Nature's Fury",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [258] = { -- Shadow (dps)
                Gems = { primary="Flawless Masterful Peridot",  meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Akil'zon's Swiftness",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Silvermoon's Alacrity",
                    [12] = "Enchant Ring - Silvermoon's Alacrity",
                    [16] = "Enchant Weapon - Jan'alai's Precision",
                },
            },
        },
        ROGUE = {
            [259] = { -- Assassination (dps)
                Gems = { primary="Flawless Quick Garnet",       meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Hex of Leeching",
                    [3]  = "Enchant Shoulders - Silvermoon's Mending",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Shaladrassil's Roots",
                    [11] = "Enchant Ring - Silvermoon's Alacrity",
                    [12] = "Enchant Ring - Silvermoon's Alacrity",
                    [16] = "Enchant Weapon - Berserker's Rage",
                    [17] = "Enchant Weapon - Berserker's Rage",
                },
            },
            [260] = { -- Outlaw (dps)
                Gems = { primary="Flawless Deadly Peridot",     meta="Powerful Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Hex of Leeching",
                    [3]  = "Enchant Shoulders - Silvermoon's Mending",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Shaladrassil's Roots",
                    [11] = "Enchant Ring - Nature's Fury",
                    [12] = "Enchant Ring - Nature's Fury",
                    [16] = "Enchant Weapon - Jan'alai's Precision",
                    [17] = "Enchant Weapon - Jan'alai's Precision",
                },
            },
            [261] = { -- Subtlety (dps)
                Gems = { primary="Flawless Quick Amethyst",     meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Eyes of the Eagle",
                    [12] = "Enchant Ring - Eyes of the Eagle",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                    [17] = "Enchant Weapon - Arcane Mastery",
                },
            },
        },
        SHAMAN = {
            [262] = { -- Elemental (dps)
                Gems = { primary="Flawless Masterful Garnet",   meta="Powerful Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Zul'jin's Mastery",
                    [12] = "Enchant Ring - Zul'jin's Mastery",
                    [16] = "Enchant Weapon - Jan'alai's Precision",
                },
            },
            [263] = { -- Enhancement (dps)
                Gems = { primary="Flawless Quick Amethyst",     meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [9]  = "Radiant Jewelbinder",
                    [11] = "Enchant Ring - Zul'jin's Mastery",
                    [12] = "Enchant Ring - Zul'jin's Mastery",
                    [16] = "Enchant Weapon - Arcane Mastery",
                    [17] = "Enchant Weapon - Berserker's Rage",
                },
            },
            [264] = { -- Restoration (healer)
                Gems = { primary="Flawless Deadly Amethyst",    meta="Telluric Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Hex of Leeching",
                    [3]  = "Enchant Shoulders - Silvermoon's Mending",
                    [5]  = "Enchant Chest - Mark of the Magister",
                    [7]  = "Arcanoweave Spellthread",
                    [8]  = "Enchant Boots - Shaladrassil's Roots",
                    [11] = "Enchant Ring - Nature's Fury",
                    [12] = "Enchant Ring - Nature's Fury",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
        },
        WARLOCK = {
            [265] = { -- Affliction (dps)
                Gems = { primary="Flawless Masterful Peridot",  meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Flight of the Eagle",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Silvermoon's Alacrity",
                    [12] = "Enchant Ring - Silvermoon's Alacrity",
                    [16] = "Enchant Weapon - Jan'alai's Precision",
                },
            },
            [266] = { -- Demonology (dps)
                Gems = { primary="Flawless Masterful Peridot",  meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Flight of the Eagle",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Silvermoon's Alacrity",
                    [12] = "Enchant Ring - Silvermoon's Alacrity",
                    [16] = "Enchant Weapon - Jan'alai's Precision",
                },
            },
            [267] = { -- Destruction (dps)
                Gems = { primary="Flawless Masterful Peridot",  meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Rune of Avoidance",
                    [3]  = "Enchant Shoulders - Flight of the Eagle",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Sunfire Silk Spellthread",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Silvermoon's Alacrity",
                    [12] = "Enchant Ring - Silvermoon's Alacrity",
                    [16] = "Enchant Weapon - Jan'alai's Precision",
                },
            },
        },
        WARRIOR = {
            [71] = { -- Arms (dps)
                Gems = { primary="Flawless Quick Garnet",       meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Hex of Leeching",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Blood Knight's Armor Kit",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Nature's Fury",
                    [12] = "Enchant Ring - Nature's Fury",
                    [16] = "Enchant Weapon - Acuity of the Ren'dorei",
                },
            },
            [72] = { -- Fury (dps)
                Gems = { primary="Flawless Quick Amethyst",     meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Hex of Leeching",
                    [3]  = "Enchant Shoulders - Amirdrassil's Grace",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Blood Knight's Armor Kit",
                    [8]  = "Enchant Boots - Lynx's Dexterity",
                    [11] = "Enchant Ring - Zul'jin's Mastery",
                    [12] = "Enchant Ring - Zul'jin's Mastery",
                    [16] = "Enchant Weapon - Arcane Mastery",
                    [17] = "Enchant Weapon - Arcane Mastery",
                },
            },
            [73] = { -- Protection (tank)
                Gems = { primary="Flawless Versatile Peridot",  meta="Indecipherable Eversong Diamond" },
                Enchants = {
                    [1]  = "Enchant Helm - Empowered Blessing of Speed",
                    [3]  = "Enchant Shoulders - Akil'zon's Swiftness",
                    [5]  = "Enchant Chest - Mark of the Worldsoul",
                    [7]  = "Forest Hunter's Armor Kit",
                    [8]  = "Enchant Boots - Farstrider's Hunt",
                    [11] = "Enchant Ring - Silvermoon's Alacrity",
                    [12] = "Enchant Ring - Silvermoon's Alacrity",
                    [16] = "Enchant Weapon - Berserker's Rage",
                },
            },
        },
    },
}
